### PR TITLE
Add `module-info.java` file

### PR DESCRIPTION
**Pull request by ielis**
Dear Phenopacket Schema development team, 
I'd like to propose adding `module-info.java` file into the project to make Phenopacket Schema a first-class citizen in the Java modular world.

The PR is really a draft, a bare minimum to make the build pass.

### CODE REVIEW

**Review by pnrobinson — APPROVED** [review]
+1 @julesjacobsen this does not affect the schema itself but makes the Java package modular.

**Comment by julesjacobsen** [comment]
Hi @ielis  can you remove the 'transitive' in the requires for protobuf. Whilst it is highly unlikely Google will add a module name, this is an automatic module name and hence if liable to change.  IntelliJ advises 'An automatic module is unreliable since it can depend on the types on the class path, and its name and exported packages can change if it's converted into an explicit module.' I think that in practice this means that users will be able to fix builds themselves should an automatic module name be changed when changed to explicit.

**Comment by ielis** [comment]
Hi @julesjacobsen , 

you're right, the automatic module names are liable for change. However, this applies to a lesser extend to libraries that have `Automatic-Module-Name` in the JAR manifest. The version of `protobuf` used in the Phenopacket Schema has the `Automatic-Module-Name` manifest entry. The developers discussed it [here](https://github.com/protocolbuffers/protobuf/pull/6568/files). So, while IntelliJ is mostly right, it is not 100% right and perhaps we should think about this. Unless Protobuf developers change their mind and use another module name, we should be OK with the transitive export. However, if we want to be extra cautious, we should remove the `transitive`.

It's unfortunate that protobuf has not been fully modularized yet because it is clear in our case that the `transitive requires` is mandated. The `com.google.protobuf.*` classes are part of schema's API (e.g. `com.google.protobuf.Timestamp` in `TimeElement`). By omitting `transitive`, we'll cause compile errors in schema's clients, unless `requires com.google.protobuf` is added to client's `module-info.java`.

So I'm afraid we're facing two options here, none of them is good.
Please let me know if you think removing `transitive` is what you'd like to do and I'll do the changes.

**Comment by julesjacobsen** [comment]
OK, we'll keep the transitive. Thanks for the PR!

**Pull request merged**
