### PR TITLE
Variant doc

### PR DESCRIPTION
**Pull request by pnrobinson**

### CODE REVIEW

**Comment by mellybelly** [comment]
@mbrush can you please review? I want to ensure generic applicability of phenopackets to all organisms and variant types.

**Comment by mbrush** [comment]
It looks pretty good to me.  One question I had was whether we might include a field for the MGI allele identifier in the **MouseAllele** message.  (I suspect this is not what the current `id` field is for - but if it is, the spec should be clear that this is where an MGI allele identifier can be captured).

Also, regarding the genotype field spec - i would consider renaming this `zygosity` if the point here is simply to capture a GENO term describing the zygosity of the indicated allele. The underlying issue here is that indicating allele zygosity suggests what the genotype of the indicated allele might be, but doesn't definitively describe the genotype in all cases.  For example, consider compound genotype comprised of two different variants at the same location, such as `fgf8a<ti282a>/fgf8a<x15>`).   Annotating with the GENO term `compound heterozygous` in this case doesn't tell you the actual genotype because you don't know what the other variant allele is.   
  
If what you really want here is to explicitly and unambiguously represent the genotype at a particular locus, then this may require modeling a proper Genotype message, instead of just a GENO zygosity term.  I am happy to make suggestions based on GENO modeling if that is the case.  But if all you really want is to know the zygosity of the indicated allele, then I would simply rename the field 'zygosity' instead of 'genotype'.

**Comment by mbrush** [comment]
Also, I think like a great example of where we can promote intra-GA4GH communication/coordination by sharing with the GKS-VR group. It could provide a great real use case to inform VR's work, and also let the Phenopackets folks benefit from the deep expertise on variant representation and standards in that group. 

As a first step, might I share the spec [here](https://github.com/phenopackets/phenopacket-schema/blob/aa3b2e0e1b609f7e00a8f87a00dd6d2d3ce16bca/docs/variant.rst) with the VR folks?  Then as needed we could set up a call or find time to chat in Hinxton- to discuss use cases and align efforts?  Thoughts @mellybelly, @pnrobinson?   It would be a shame if VR didn't produce something that works for such an important and core driver as Phenopackets.

**Comment by pnrobinson** [comment]
@mbrush sure please share everything-- feedback would be great. Can we try to see if there are any other suggestions before the Hinxton meeting so that we can hopefully make some final decisions there? @julesjacobsen the zygosity suggestion is good, that is actually what we mean, although perhaps the word is less frequently used.

**Comment by pnrobinson** [comment]
actually genotype is not wrong, the word can apply to an allele, locus, gene, etc.etc @mbrush how do you define genotype?

**Comment by julesjacobsen** [comment]
I think Matt has a point. Thinking about how the [VMC](https://docs.google.com/document/d/12E8WbQlvfZWk5NrxwLytmympPby6vsv60RxCeD5wc1E/edit#heading=h.87qvo3b43kw9) are defining things, I think they'd use the term ```Haplotype```. I think this is roughly accurate portrayal of VMC:

```proto
message Genotype {
  repeated Haplotype haplotypes = 1;
}

message Haplotype {
  repeated Allele alleles = 1;
}

message Allele {
  string id = 1;
  // the ID of the Location
  string loc_id = 2;
  // the sequence at this location
  string state = 3;
}

message Location {
  string id = 1;
  Interval interval = 2;
  string sequence_id= 3;
}

message Interval {
  int32 start = 1;
  int32 end = 2;
}
```

**Comment by julesjacobsen** [comment]
And the MME also use the term ```zygosity``` modeled as an integer, modeled in a very similar fashion to what we have arrived at

https://github.com/phenopackets/phenopacket-schema/blob/ecf4ea853e1f7faad35034a67fa3763cdd332649/src/test/proto/org/matchmakerexchange/api/v1/mme.proto#L27-L47

**Pull request merged**
