### PR TITLE
Update base.proto to include phenopacket_schema_version

### PR DESCRIPTION
**Pull request by drseb**
See https://github.com/phenopackets/phenopacket-schema/issues/131

### CODE REVIEW

**Comment by drseb** [comment]
ping @pnrobinson @julesjacobsen

**Comment by pnrobinson** [comment]
@julesjacobsen  This makes sense to me. I think that the validation code should also require this element. I wonder if it would be better to put the element in all top level constructs that might be used independently?

**Comment by julesjacobsen** [comment]
The big issue I have with this is that there is no way to verify that this is correct. This isn't really the way protobuf is supposed to work. The idea is that as long as the namespace is the same i.e. `org.phenopackets.v1` the message will be understood, to the best of the receiver's knowledge. Please read the docs on what 'schema evolution' is supposed to achieve. To quote:

> Importantly, the protocol buffer format supports the idea of extending the format over time in such a way that the code can still read data encoded with the old format. 

So the version doesn't necessarily make a lot of sense.

**Comment by pnrobinson** [comment]
@julesjacobsen But if we know that v42 ands v43 are both compatible with org.phenopackets.v1, then we can figure out that a v42 message might be lacking something we added for v43. Is there any other way of doing this?

**Comment by drseb** [comment]
@julesjacobsen what exactly is your suggestion? How can I find out which python version was used to generate a phenopacket? Should we always contact the data creators and ask them? (they will tell me "0.4" and it would in fact make a lot of sense for me)

**Comment by cmungall** [comment]
@julesjacobsen do your comments apply to the JSON serialization? We haven't explicitly articulated this but I suspect many users of phenopackets will be JSON rather than sending protobuf messages.

**Pull request merged**
