### PR TITLE
Update base.proto

### PR DESCRIPTION
**Pull request by drseb**
Related to https://github.com/phenopackets/phenopacket-schema/issues/40

### CODE REVIEW

**Comment by drseb** [comment]
We would actually prefer to have multiple fields: Ideally we would like to have 2 different separated fields, one for the "group / project level information" and one for the "data owner". Would this be possible? Who decides this?

**Comment by cmungall** [comment]
This seems reasonable. Do we think we know in advance all possible metadata fields here? The other option is a generic attribute-value model which will be future-proofed, but harder to work with.

Note you PR increments existing numbers. I believe we want to avoid this thing once we make a v1.0.0 release

**Comment by julesjacobsen** [comment]
@drseb can you give an example of the multiple fields?

**Comment by drseb** [comment]
in our case examples look like this:

- _group / project level information_: ERN-EYE
- _data owner_: University of Geilenkirchen

**Pull request merged**
